# Generated by Django 6.0.3 on 2026-04-10 14:00

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_id',
            field=models.CharField(default=students.models.generate_academic_id, max_length=20, unique=True, verbose_name='الرقم الأكاديمي'),
        ),
    ]
