# Generated by Django 6.0.3 on 2026-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0002_hash_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='students.student', verbose_name='الطلاب المُسندون'),
        ),
    ]
